task:
    resource: "@TaskBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
task_planer:
    path:     /task_planner
    defaults: { _controller: FOSUserBundle:Security:login }